const QuizData = [
    {
        question: "What is the capital of Nigeria",
        option_a: "New York",
        option_b: "Delhi",
        option_c: "Abuja",
        option_d: "Free Town",
        correct_answer: "Abuja",
    },
    {
        question: "Who is Jackie Chan?",
        option_a: "A wrestler",
        option_b: "A musician",
        option_c: "A footballer",
        option_d: "An actor",
        correct_answer: "An actor",
    },
    {
        question: "What is 70 degrees Fahrenheit in Celsius?",
        option_a: "18.8889",
        option_b: "20",
        option_c: "21.111",
        option_d: "158",
        correct_answer: "21.111",
    },
    {
        question: "When was Mahatma Ghandi born?",
        option_a: "October 2, 1869",
        option_b: "December 15, 1872",
        option_c: "July 18, 1918",
        option_d: "January 15, 1929",
        correct_answer: "October 2, 1869",
    },
    {
        question: "What is 65 times 52?",
        option_a: "117",
        option_b: "3120",
        option_c: "3380",
        option_d: "3520",
        correct_answer: "3380",
    },
    {
        question: "When did the Avengers come out?",
        option_a: "May 2, 2008",
        option_b: "May 4, 2012",
        option_c: "May 3, 2013",
        option_d: "April 4, 2014",
        correct_answer: "May 4, 2012",
    },
    {
        question: "How far is the moon from Earth?",
        option_a: "7,918 miles (12,742 km)",
        option_b: "86,881 miles (139,822 km)",
        option_c: "238,400 miles (384,400 km)",
        option_d: "5,980,000 miles (57,910,000 km)",
        correct_answer: "86,881 miles (139,822 km)",
    },
    {
        question: "What is 65 times 52?",
        option_a: "117",
        option_b: "3120",
        option_c: "3380",
        option_d: "3520",
        correct_answer: "3380",
    },
    {
        question: "What is the scientific name of a butterfly?",
        option_a: "Apis",
        option_b: "Coleoptera",
        option_c: "Formicidae",
        option_d: "Rhopalocera",
        correct_answer: "Rhopalocera",
    },
    {
        question: "What is the capital of Nigeria",
        option_a: "New York",
        option_b: "Delhi",
        option_c: "Abuja",
        option_d: "Free Town",
        correct_answer: "Abuja",
    },
    {
        question: "Who is Jackie Chan?",
        option_a: "A wrestler",
        option_b: "A musician",
        option_c: "A footballer",
        option_d: "An actor",
        correct_answer: "An actor",
    },
    {
        question: "What is 70 degrees Fahrenheit in Celsius?",
        option_a: "18.8889",
        option_b: "20",
        option_c: "21.111",
        option_d: "158",
        correct_answer: "21.111",
    },
    {
        question: "When was Mahatma Ghandi born?",
        option_a: "October 2, 1869",
        option_b: "December 15, 1872",
        option_c: "July 18, 1918",
        option_d: "January 15, 1929",
        correct_answer: "October 2, 1869",
    },
    {
        question: "What is 65 times 52?",
        option_a: "117",
        option_b: "3120",
        option_c: "3380",
        option_d: "3520",
        correct_answer: "3380",
    },
    {
        question: "When did the Avengers come out?",
        option_a: "May 2, 2008",
        option_b: "May 4, 2012",
        option_c: "May 3, 2013",
        option_d: "April 4, 2014",
        correct_answer: "May 4, 2012",
    },
    {
        question: "How far is the moon from Earth?",
        option_a: "7,918 miles (12,742 km)",
        option_b: "86,881 miles (139,822 km)",
        option_c: "238,400 miles (384,400 km)",
        option_d: "5,980,000 miles (57,910,000 km)",
        correct_answer: "86,881 miles (139,822 km)",
    },
    {
        question: "What is 65 times 52?",
        option_a: "117",
        option_b: "3120",
        option_c: "3380",
        option_d: "3520",
        correct_answer: "3380",
    },
    {
        question: "What is the scientific name of a butterfly?",
        option_a: "Apis",
        option_b: "Coleoptera",
        option_c: "Formicidae",
        option_d: "Rhopalocera",
        correct_answer: "Rhopalocera",
    },
    {
        question: "What is the capital of Nigeria",
        option_a: "New York",
        option_b: "Delhi",
        option_c: "Abuja",
        option_d: "Free Town",
        correct_answer: "Abuja",
    },
    {
        question: "Who is Jackie Chan?",
        option_a: "A wrestler",
        option_b: "A musician",
        option_c: "A footballer",
        option_d: "An actor",
        correct_answer: "An actor",
    },
    {
        question: "What is 70 degrees Fahrenheit in Celsius?",
        option_a: "18.8889",
        option_b: "20",
        option_c: "21.111",
        option_d: "158",
        correct_answer: "21.111",
    },
    {
        question: "When was Mahatma Ghandi born?",
        option_a: "October 2, 1869",
        option_b: "December 15, 1872",
        option_c: "July 18, 1918",
        option_d: "January 15, 1929",
        correct_answer: "October 2, 1869",
    },
    {
        question: "What is 65 times 52?",
        option_a: "117",
        option_b: "3120",
        option_c: "3380",
        option_d: "3520",
        correct_answer: "3380",
    },
    {
        question: "When did the Avengers come out?",
        option_a: "May 2, 2008",
        option_b: "May 4, 2012",
        option_c: "May 3, 2013",
        option_d: "April 4, 2014",
        correct_answer: "May 4, 2012",
    },
    {
        question: "How far is the moon from Earth?",
        option_a: "7,918 miles (12,742 km)",
        option_b: "86,881 miles (139,822 km)",
        option_c: "238,400 miles (384,400 km)",
        option_d: "5,980,000 miles (57,910,000 km)",
        correct_answer: "86,881 miles (139,822 km)",
    },
    {
        question: "What is 65 times 52?",
        option_a: "117",
        option_b: "3120",
        option_c: "3380",
        option_d: "3520",
        correct_answer: "3380",
    },
    {
        question: "What is the scientific name of a butterfly?",
        option_a: "Apis",
        option_b: "Coleoptera",
        option_c: "Formicidae",
        option_d: "Rhopalocera",
        correct_answer: "Rhopalocera",
    },
    {
        question: "What is the capital of Nigeria",
        option_a: "New York",
        option_b: "Delhi",
        option_c: "Abuja",
        option_d: "Free Town",
        correct_answer: "Abuja",
    },
    {
        question: "Who is Jackie Chan?",
        option_a: "A wrestler",
        option_b: "A musician",
        option_c: "A footballer",
        option_d: "An actor",
        correct_answer: "An actor",
    },
    {
        question: "What is 70 degrees Fahrenheit in Celsius?",
        option_a: "18.8889",
        option_b: "20",
        option_c: "21.111",
        option_d: "158",
        correct_answer: "21.111",
    },
]


export default QuizData